import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
ObSave — Ad Astra Forge
*/
`;

const prod = process.argv[2] === "production";

const googleClientId = process.env.OBSAVE_GOOGLE_CLIENT_ID ?? "";
const googleClientSecret = process.env.OBSAVE_GOOGLE_CLIENT_SECRET ?? "";

const nodeExternals = [
	"obsidian",
	"electron",
	"http",
	"https",
	"url",
	"crypto",
	"net",
	"tls",
	"fs",
	"path",
	"buffer",
	"events",
	"process",
	"stream",
	"util",
	"querystring",
	"string_decoder",
];

const codemirrorExternals = [
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
];

const sharedOptions = {
	banner: {
		js: banner,
	},
	define: {
		__OBSAVE_GOOGLE_CLIENT_ID__: JSON.stringify(googleClientId),
		__OBSAVE_GOOGLE_CLIENT_SECRET__: JSON.stringify(googleClientSecret),
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	platform: "browser",
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	external: [...nodeExternals, ...codemirrorExternals],
};

if (prod) {
	await esbuild.build(sharedOptions);
	process.exit(0);
} else {
	const context = await esbuild.context(sharedOptions);
	await context.watch();
}
